# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=50, verbose_name='ID User')),
                ('IdCampana', models.CharField(max_length=50, verbose_name='ID Campa\xf1a')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('idMensaje', models.CharField(max_length=50, verbose_name='ID Mensaje')),
            ],
            options={
                'verbose_name': 'Notificaci\xf3n',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='services.Notification', verbose_name='Notificaci\xf3n')),
            ],
            options={
                'verbose_name': 'Par\xe1metro',
                'verbose_name_plural': 'Par\xe1metros',
            },
        ),
    ]
